interface Icons {
    [key: string]: string;
}

module MapIcons {
    let basepath = "./static/img/map-icons/";

    let icons:Icons = {
        airport: "airport.png",
        airportsmall: "aircraftsmall.png",
        aquarium: "aquarium.png",
        artGallery: "artgallery.png",
        bar: "bar.png",
        beach: "breach.png",
        bicycle: "cycling.png",
        camping: "camping2.png",
        car: "car.png",
        casino: "poker.png",
        castle: "castle-2.png",
        cave: "cave-2.png",
        cemetary: "cemetary.png",
        church: "chapel-2.png",
        cinema: "cinema.png",
        citysquare: "citysquare.png",
        cocktail: "bar-coktail.png",
        coffee: "coffee.png",
        cruise: "cruiseship.png",
        currency: "currencyexchange.png",
        desert: "desert-2.png",
        handicaped: "disability.png",
        farm: "farm-2.png",
        food: "fastfood.png",
        themepark: "ferriswheel.png",
        ferry: "ferry.png",
        festival: "festival.png",
        medical: "firstaid.png",
        fishing: "fishing.png",
        garden: "flower.png",
        foodtruck: "foodtruck.png",
        forest: "forest-2.png",
        fountain: "foutain-2.png",
        golf: "golfing.png",
        hotel: "motel-2.png",
        heliport: "helicopter.png",
        hiking: "hiking.png",
        hunting: "hunting.png",
        skating: "skating.png",
        music: "jazzclub.png",
        karting: "karting.png",
        lake: "lake.png",
        landmark: "landmark.png",
        library: "library.png",
        mall: "mall.png",
        marina: "marina-2.png",
        memorial: "modernmemorial.png",
        motorcycle: "motorcycle.png",
        mountain: "mountains.png",
        mural: "mural.png",
        museum: ".png",
        observatory: "observatory.png",
        parc: "flower.png",
        parking: "parkinggarage.png",
        planetarium: "planetarium-2.png",
        playground: "playground.png",
        port: "harbor.png",
        residential: "appartment.png",
        resort: "resort.png",
        restaurant: "restaurant.png",
        river: "river-2.png",
        archeology: "ruins-2.png",
        sailing: "sailing.png",
        sauna: "sauna.png",
        shooting: "shootingrange.png",
        skiing: "skiing.png",
        spa: "spa.png",
        stadium: "stadium.png",
        statue: ".png",
        taxi: "taxiway.png",
        tea: "teahouse.png",
        telephone: "telephone.png",
        theater: "theater.png",
        toilets: "toilets.png",
        train: "train.png",
        school: "university.png",
        vineyard: "vineyard-2.png",
        volcano: "volcano-2.png",
        waterpark: "waterpark.png",
        wine: "winebar.png",
        unesco: "worldheritagesite.png",
        viewpoint: "binoculars.png",
        youarehere: "you-are-here-2.png",
        zoo: "zoo.png"
    };

    export function getIcon(category: string) : string {
        return basepath + icons[category];
    }

    export function getYouAreHereIcon() : string {
        return getIcon("youarehere");
    }
}